eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
#     cluster: feign
     cluster: ribbon
server:
  port: 8766
spring:
  application:
    name: demo-client-feign

management:
  endpoints:
    web:
      exposure:
        include[0]: "hystrix.stream"
        include[1]: "health"
        include[2]: "info"

feign:
  hystrix:
    enabled: true
