eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
     cluster: ribbon
     
server:
  port: 8768
spring:
  application:
    name: demo-ribbon-2
    
management:
  endpoints:
    web:
      exposure:
        include[0]: "hystrix.stream"
        include[1]: "health"
        include[2]: "info"

#turbine:
#  # 指定了要监控的应用名字
#  app-config: demo-client
#  # 表示集群的名字为default
#  cluster-name-expression: new String("default")
#  # 表示同一主机上的服务通过host和port的组合来进行区分，默认情况下是使用host来区分，这样会使本地调试有问题
##  combine-host-port: true
#  instanceUrlSuffix: /hystrix.stream